version: '3'
services:
  app:
    image: qr:v1
    container_name: qr
    ports: 
      - 8080:8080 
    restart: on-failure
    depends_on:
      - mysql          
    volumes:
      - .:/webapp_check-in
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=mysql'
      - 'DB_LOGIN=root'
      - 'DB_PASS=root'

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: web-app_check-in
    volumes:
      #- "/c/mysql-data:/var/lib/mysql"
      - ./mysqldata:/var/lib/mysql

  pma:
        image: phpmyadmin/phpmyadmin
        depends_on:
          - mysql
        ports:
          - 5003:80
        environment:
          - 'PMA_HOST=mysql'
          - 'PMA_PORT=3306'
        container_name: myadmin

volumes:
  mysqldata:      